# Generated by Django 4.2.7 on 2023-11-21 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0006_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_ceo',
            field=models.CharField(default=datetime.datetime(2023, 11, 21, 11, 43, 8, 961953, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_established',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 11, 44, 19, 980910, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(default=datetime.datetime(2023, 11, 21, 11, 44, 35, 283705, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
