# Generated by Django 4.2.7 on 2023-11-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0009_job_seeker_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='job_seekers_bookmarked', to='venari.post_jobs'),
        ),
    ]
