# Generated by Django 4.2.7 on 2023-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0013_job_seeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
