# Generated by Django 4.2.7 on 2023-11-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0014_alter_apply_job_resume_alter_job_seeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
