# Generated by Django 4.2.7 on 2023-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0015_apply_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
