# Generated by Django 4.2.7 on 2023-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0016_job_seeker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='experience',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='years_experience',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
