# Generated by Django 4.2.7 on 2023-12-12 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0018_alter_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
