# Generated by Django 4.2.7 on 2023-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venari', '0019_job_seeker_company_name_job_seeker_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='company_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
